server:
  host: "0.0.0.0"
  port: "8080"

storage:
  videos_dir: "@videos"
  raw_dir: "raw"
  hls_dir: "hls"

upload:
  max_size_mb: 1024
  allowed_extensions:
    - ".mp4"
    - ".mov"
    - ".mkv"
    - ".webm"

ffmpeg:
  hls_time: 4
  video_codec: "libx264"
  audio_codec: "aac"
